In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# 데이터 불러오기

df24 = pd.read_csv("./2024 승하차인원(1_8호선).csv")
df23 = pd.read_csv("./2023 승하차인원(1_8호선).csv")
df22 = pd.read_csv("./2022 승하차인원(1_8호선).csv")
df21 = pd.read_csv("./2021 승하차인원(1_8호선).csv")
df20 = pd.read_csv("./2020 승하차인원(1_8호선).csv")
df19 = pd.read_csv("./2019 승하차인원(1_8호선).csv")
df18 = pd.read_csv("./2018 승하차인원(1_8호선).csv")
df24_1 = pd.read_csv("./2024 분기별 승차인원 sorted.csv")
df24_2 = pd.read_csv("./2024 분기별 하차인원 sorted.csv")
df23_1 = pd.read_csv("./2023 분기별 승차인원 sorted.csv")
df23_2 = pd.read_csv("./2023 분기별 하차인원 sorted.csv")
df22_1 = pd.read_csv("./2022 분기별 승차인원 sorted.csv")
df22_2 = pd.read_csv("./2022 분기별 하차인원 sorted.csv") 
df21_1 = pd.read_csv("./2021 분기별 승차인원 sorted.csv")
df21_2 = pd.read_csv("./2021 분기별 하차인원 sorted.csv")
df20_1 = pd.read_csv("./2020 분기별 승차인원 sorted.csv")
df20_2 = pd.read_csv("./2020 분기별 하차인원 sorted.csv")
df19_1 = pd.read_csv("./2019 분기별 승차인원 sorted.csv")
df19_2 = pd.read_csv("./2019 분기별 하차인원 sorted.csv")
df18_1 = pd.read_csv("./2018 분기별 승차인원 sorted.csv")
df18_2 = pd.read_csv("./2018 분기별 하차인원 sorted.csv")

In [ ]:
# 출근 시간대 사람들이 가장 많이 타고 내리는 역은 어디일까?
# 연도별 호선별 이용객 수
# 1호선의 지하철역 중에서 승차인원수가 가장 많은 역은 어디일까?
# 시간별 전체역 승객 평균 수
# 평균 승하차 인원수 Top10
# 시간대별로 사람들이 가장 많이 타고 내리는 역은 어디일까?
# 시간대별 하차 인원이 가장 많은 역은 어디일까?
# 시간대별로 사람들이 가장 많이 타고 내리는 역은 어디일까? (지하철 시간대별 승하차 추이)
# 이용객 수 시각화 및 분석:
지하철 이용객 수의 시간대별, 요일별, 혹은 계절별 변화를 시각화하고 분석합니다. 특정 시간대나 요일에 이용객 수가 많은 이유를 찾아봅니다.
#밤 11시에 사람들이 가장 많이 타는 역은 어디일까?
#모든 지하철역에서 시간대별 승하차 인원을 모두 더하면
# 코로나 재택근무 2020년 2분기~2022년 1분기까지가 코로나. 월로 따지면 2020년 3월~2022년 4월. 코로나 이전, 코로나 시기, 코로나 이후 3개로 나눠서
#코로나 이후 취업이 잘되는 분야나 안되는 분야가 달라짐. 그래서 출퇴근역이 달라짐 (강사)
#

##### 출근 시간대 사람들이 가장 많이 타고 내리는 역은 어디일까?

2023년

In [16]:
df23_1

,날짜,호선,역명,구분,06시 이전,06시-07시,07시-08시,08시-09시,09시-10시,10시-11시,...,20시-21시,21시-22시,22시-23시,23시-24시,24시 이후,연도,월,일,요일,분기
0,2023-01-01,2호선,홍대입구역,승차,4640,2816,1434,1078,1201,1214,...,4443,4730,4452,1914,22,2023,1,1,일,1
1,2023-03-12,2호선,홍대입구역,승차,2048,1189,805,799,1204,1510,...,5466,5622,5027,2279,22,2023,3,12,일,1
2,2023-03-26,2호선,홍대입구역,승차,1928,1160,866,981,1435,1763,...,6002,6595,5426,2514,22,2023,3,26,일,1
3,2023-01-15,2호선,홍대입구역,승차,1801,1117,745,849,1074,1290,...,5637,6342,5404,2386,32,2023,1,15,일,1
4,2023-03-19,2호선,홍대입구역,승차,1775,1253,876,1021,1409,1744,...,6071,6457,5812,2543,33,2023,3,19,일,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82683,2023-10-12,5호선,동대문역사문화공원역,승차,3,25,58,102,96,88,...,204,182,112,52,8,2023,10,12,목,4
82684,2023-10-20,4호선,동작역,승차,3,24,101,127,148,79,...,77,66,65,25,13,2023,10,20,금,4
82685,2023-10-22,5호선,동대문역사문화공원역,승차,3,16,30,71,141,95,...,61,38,37,18,0,2023,10,22,일,4
82686,2023-10-03,5호선,동대문역사문화공원역,승차,3,3,19,31,83,54,...,38,29,43,23,0,2023,10,3,화,4
82687,2023-10-26,5호선,동대문역사문화공원역,승차,2,19,40,100,100,97,...,145,156,120,50,7,2023,10,26,목,4